// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealWorthspace.Data;

#nullable disable

namespace realworth.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RealWorthspace.Models.ExchangeRate", b =>
                {
                    b.Property<string>("currency_code")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("currency_code");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("RealWorthspace.Models.PPPData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("currency_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("currency_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("PPP");
                });
#pragma warning restore 612, 618
        }
    }
}
